---
- name: Install nginx
  ansible.builtin.import_role:
    name: nginxinc.nginx

- name: Copy nginx load balancer config
  ansible.builtin.template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/conf.d/load-balancer.conf
    owner: root
    group: root
    mode: 0644

- name: Delete default nginx config
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Add nginx certs
  ansible.builtin.copy:
    content: "{{ item.variable }}"
    dest: "{{ item.dest }}"
    mode: '0777'
    owner: root
  loop:
    - { dest: "/etc/nginx/privkey.pem", variable: "{{ cert_key }}" }
    - { dest: "/etc/nginx/fullchain.pem", variable: "{{ cert }}" }
  no_log: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
